from datetime import datetime
from typing import Dict, Any, Optional, List
from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from loguru import logger

from backend.models.delayed_effects import ScheduledEvent
from backend.models.world_models import WorldState, StructuredWorldState, WorldEventRecord
from backend.systems.public_opinion_system import PublicOpinionSystem

class DelayedEffectSystem:
    """Manages scheduled events that trigger consequences on future simulation steps."""

    def __init__(self):
        self.public_opinion_system = PublicOpinionSystem()

    async def schedule(
        self,
        db: AsyncSession,
        project_id: UUID,
        trigger_turn: int,
        event_type: str,
        description: str,
        impact_data: Dict[str, Any],
        visibility: float = 0.5,
        cause_action_id: Optional[UUID] = None,
    ):
        """Schedule a future consequence event."""
        event = ScheduledEvent(
            project_id=project_id,
            trigger_turn=trigger_turn,
            event_type=event_type,
            description=description,
            impact_data=impact_data,
            visibility=visibility,
            cause_action_id=cause_action_id,
        )
        db.add(event)
        await db.commit()
        logger.info(f"Scheduled delayed event '{event_type}' for step {trigger_turn}")

    async def check_and_fire(
        self,
        db: AsyncSession,
        current_step: int,
        project_id: UUID,
        world_state: WorldState,
    ):
        """Call this at the START of every simulation step."""
        # Get pending events
        result = await db.execute(
            select(ScheduledEvent).where(
                ScheduledEvent.project_id == project_id,
                ScheduledEvent.is_fired == False,
                ScheduledEvent.trigger_turn <= current_step,
            )
        )
        events = result.scalars().all()
        
        if not events:
            return

        logger.info(f"Firing {len(events)} delayed events for step {current_step}")
        structured = self._get_structured_state(world_state)
        
        for ev in events:
            extra_events = self._apply_impact(structured, ev.impact_data)
            ev.is_fired = True
            ev.fired_at = datetime.utcnow()
            
            # Add to visible world events
            structured.recent_events.append(WorldEventRecord(
                step=current_step,
                actor="system",
                action=ev.event_type,
                outcome=ev.description,
                visibility=ev.visibility
            ))
            
            # Add any extra events generated by impact (like opinion tipping points)
            for extra in extra_events:
                structured.recent_events.append(WorldEventRecord(
                    step=current_step,
                    actor="system",
                    action="opinion_shift",
                    outcome=extra,
                    visibility=1.0
                ))
            logger.info(f"Fired delayed event: {ev.event_type} - {ev.description}")
            
        self._save_structured_state(world_state, structured)
        await db.commit()

    def _apply_impact(self, structured: StructuredWorldState, impact_data: Dict[str, Any]) -> List[str]:
        """Apply payload changes to the structured world state. Returns extra event messages."""
        extra_events = []
        if not impact_data:
            return extra_events

        if "public_opinion" in impact_data:
            for topic, delta in impact_data["public_opinion"].items():
                event_msg = self.public_opinion_system.push_opinion(structured, topic, delta)
                if event_msg:
                    extra_events.append(event_msg)
                
        if "market_conditions" in impact_data:
            for sector, delta in impact_data["market_conditions"].items():
                current = structured.market_conditions.get(sector, 0.5)
                structured.market_conditions[sector] = max(0.0, min(1.0, current + delta))
                
        if "regulatory_pressure" in impact_data:
            for entity, delta in impact_data["regulatory_pressure"].items():
                current = structured.regulatory_pressure.get(entity, 0.0)
                structured.regulatory_pressure[entity] = max(0.0, min(1.0, current + delta))
                
        return extra_events

    def _get_structured_state(self, world_state: WorldState) -> StructuredWorldState:
        """Get or create structured world state"""
        if not world_state or not world_state.state:
            return StructuredWorldState()
        
        if isinstance(world_state.state, dict) and "agent_resources" in world_state.state:
            return StructuredWorldState.from_dict(world_state.state)
        
        return StructuredWorldState.from_legacy_state(world_state.state)

    def _save_structured_state(self, world_state: WorldState, structured: StructuredWorldState):
        """Save structured state back to WorldState object"""
        if world_state:
            world_state.state = structured.to_dict()
